# Generated by Django 4.1.3 on 2022-11-13 06:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0005_emergency_userinfo_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='emergency_type',
            field=models.CharField(choices=[(0, 'Normal'), (1, 'Animal_Spotting'), (2, 'Health_EMERGENCY'), (3, 'Theft'), (4, 'Other')], default=0, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emergency',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='profession',
            unique_together={('id', 'profession_name')},
        ),
    ]
