# Generated by Django 4.1.3 on 2022-11-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_emergency_emergency_type_emergency_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergency',
            name='emergency_type',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Animal_Spotting'), (2, 'Health_Emergency'), (3, 'Theft'), (4, 'Other')]),
        ),
    ]
