# Generated by Django 4.1.3 on 2022-11-13 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_alter_emergency_emergency_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=125)),
                ('profession', models.IntegerField(null=True)),
                ('wantstohelp', models.BooleanField()),
                ('password', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.CharField(default=True, max_length=30)),
                ('email', models.CharField(default='hari.deepak1@gmail.com', max_length=25)),
                ('tokenid', models.CharField(max_length=25, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
