# Generated by Django 4.1.3 on 2022-11-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_userdata_remove_emergency_user_id_delete_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='tokenid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
