# Generated by Django 4.1.3 on 2022-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_alter_userdata_tokenid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='tokenid',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
